name: Checks

on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  markdown-check:
    name: Check Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Lint markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: './.markdownlint.yml'
          args: .
  ampersands-check:
    name: Check Ampersands are Unescaped
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Run Python Ampersands Script
        run: python3 scripts/check_ampersands.py
